[Variables]
TotalGame=10

Gamecover1=5a784ec0690086599e28f84b.png
Gamedir1=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

Gamecover2=game-maker.png
Gamedir2=D:\Program Files\GameMaker-Studio\Startilla_V3.exe

Gamecover3=28385575-9d11e2be-6c96-11e7-9883-dad6ea89ba23.png
Gamedir3=D:\Program Files\Editor\Unity.exe

Gamename4=GM:Studio
Gamecover4=Discord-Logo-Color.png
Gamedir4="C:\Users\Finch\AppData\Local\Discord\Update.exe" "--processStart" "Discord.exe"

Gamecover5=Spotify.png
Gamedir5=C:\Users\Finch\AppData\Roaming\Spotify\Spotify.exe

Gamecover6=gaming.png
Gamedir6=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

Gamecover7=document.png
Gamedir7=E:\Google Drive\Notes.txt

Gamecover8=VLC-Media-Player-icon.png
Gamedir8=C:\Program Files\VideoLAN\VLC\vlc.exe

Gamecover9=download.png
Gamedir9=C:\Users\Finch\Downloads

Gamecover10=unikey.ico
Gamedir10=D:\Program Files\UniKeyNT.exe

Gamecover11=PC.png
Gamedir11=#@#PC.lnk

Gamecover12=setting.png
Gamedir12=ms-settings:
